### ISSUE TITLE
Use cl-lib for conformance with elisp coding conventions

### ISSUE THREAD

**Issue by memeplex** [kiwanami/emacs-deferred#24]
Just that.

http://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html

**Comment by AdrieanKhisbe** [comment]
> $ touch this

Little poke since emacs 24.5 got released.

@kiwanami, I can take care of this if you want.
And maybe rename function to follow elisp-conventions :)

**Comment by kiwanami** [comment]
I make v0.4.0 with the current status to maintain compatibility with Emacs 23.
Toward the next version, I would drop Emacs 23 support and replacing `cl-lib`.
(it seems to be very big task...)

**Comment by AdrieanKhisbe** [comment]
:+1: :smiley:

**Comment by phst** [comment]
Hi, since v0.4.0 (and Emacs 25) has been released a while ago, do you still plan to drop Emacs 23 compatibility in the master branch? Thanks!

**Comment by kiwanami** [comment]
Hi @phst 
Thank you for your comment. I'll check your PR.
