### ISSUE TITLE
Outdated v0.3.1 release in marmalade repo

### ISSUE THREAD

**Issue by liblit** [kiwanami/emacs-deferred#46]
The latest stable release is [v0.5.1](https://github.com/kiwanami/emacs-deferred/releases/tag/v0.5.1), but the [marmalade Emacs package repository](https://marmalade-repo.org/) only offers v0.3.1. Can the latter be updated or removed? In my opinion, removing `deferred` from marmalade entirely is a fine option, since [MELPA Stable](https://stable.melpa.org/) already [offers v0.5.1](https://stable.melpa.org/#/deferred).

**Comment by kiwanami** [comment]
OK. I'd remove `deferred` from the marmalade repo.

Hmm, I could not find package removal UI.
I'll try the web API.
https://marmalade-repo.org/docs

**Comment by liblit** [comment]
Thank you!
